PULP_APP = test
PULP_APP_SRCS = core_list_join.c core_main.c core_matrix.c core_state.c core_util.c

PULP_APP_SRCS += pulp/core_portme.c 
PULP_CFLAGS +=  -I$(CURDIR) -I$(CURDIR)/pulp
PULP_CFLAGS += -DITERATIONS=1000
PULP_CFLAGS += -O3 -falign-functions=16 -funroll-all-loops
PULP_CFLAGS += -DFLAGS_STR="\"NOT IMPLEMENTED\"" -DCLOCKS_PER_SEC=100000000 -DMULTITHREAD=1 -DCOMPILER_VERSION="\"na\"" -DCOMPILER_FLAGS="\"na\""

include $(PULP_SDK_HOME)/install/rules/pulp_rt.mk

